export interface ReferenceEntry {
  command: string; // the LaTeX command a player types, e.g. String.raw`\alpha` — NO $ delimiters, authored with String.raw
  name?: string; // optional short human name, e.g. "alpha", "for all", "integral"
}

export interface ReferenceCategory {
  name: string; // e.g. "Greek letters"
  entries: ReferenceEntry[];
}

export const reference: ReferenceCategory[] = [
  {
    name: "Greek letters",
    entries: [
      { command: String.raw`\alpha`, name: "alpha" },
      { command: String.raw`\beta`, name: "beta" },
      { command: String.raw`\gamma`, name: "gamma" },
      { command: String.raw`\delta`, name: "delta" },
      { command: String.raw`\epsilon`, name: "epsilon" },
      { command: String.raw`\varepsilon`, name: "var epsilon" },
      { command: String.raw`\zeta`, name: "zeta" },
      { command: String.raw`\eta`, name: "eta" },
      { command: String.raw`\theta`, name: "theta" },
      { command: String.raw`\vartheta`, name: "var theta" },
      { command: String.raw`\iota`, name: "iota" },
      { command: String.raw`\kappa`, name: "kappa" },
      { command: String.raw`\lambda`, name: "lambda" },
      { command: String.raw`\mu`, name: "mu" },
      { command: String.raw`\nu`, name: "nu" },
      { command: String.raw`\xi`, name: "xi" },
      { command: String.raw`\pi`, name: "pi" },
      { command: String.raw`\varpi`, name: "var pi" },
      { command: String.raw`\rho`, name: "rho" },
      { command: String.raw`\sigma`, name: "sigma" },
      { command: String.raw`\tau`, name: "tau" },
      { command: String.raw`\upsilon`, name: "upsilon" },
      { command: String.raw`\phi`, name: "phi" },
      { command: String.raw`\varphi`, name: "var phi" },
      { command: String.raw`\chi`, name: "chi" },
      { command: String.raw`\psi`, name: "psi" },
      { command: String.raw`\omega`, name: "omega" },
      { command: String.raw`\Gamma`, name: "capital Gamma" },
      { command: String.raw`\Delta`, name: "capital Delta" },
      { command: String.raw`\Theta`, name: "capital Theta" },
      { command: String.raw`\Lambda`, name: "capital Lambda" },
      { command: String.raw`\Xi`, name: "capital Xi" },
      { command: String.raw`\Pi`, name: "capital Pi" },
      { command: String.raw`\Sigma`, name: "capital Sigma" },
      { command: String.raw`\Upsilon`, name: "capital Upsilon" },
      { command: String.raw`\Phi`, name: "capital Phi" },
      { command: String.raw`\Psi`, name: "capital Psi" },
      { command: String.raw`\Omega`, name: "capital Omega" },
    ],
  },
  {
    name: "Operators & relations",
    entries: [
      { command: String.raw`\times`, name: "times" },
      { command: String.raw`\div`, name: "divide" },
      { command: String.raw`\pm`, name: "plus minus" },
      { command: String.raw`\mp`, name: "minus plus" },
      { command: String.raw`\cdot`, name: "dot product" },
      { command: String.raw`\ast`, name: "asterisk" },
      { command: String.raw`\leq`, name: "less than or equal" },
      { command: String.raw`\geq`, name: "greater than or equal" },
      { command: String.raw`\neq`, name: "not equal" },
      { command: String.raw`\approx`, name: "approximately" },
      { command: String.raw`\equiv`, name: "equivalent" },
      { command: String.raw`\sim`, name: "similar" },
      { command: String.raw`\simeq`, name: "similar equal" },
      { command: String.raw`\cong`, name: "congruent" },
      { command: String.raw`\propto`, name: "proportional to" },
      { command: String.raw`\ll`, name: "much less than" },
      { command: String.raw`\gg`, name: "much greater than" },
      { command: String.raw`\subset`, name: "subset" },
      { command: String.raw`\subseteq`, name: "subset or equal" },
      { command: String.raw`\supset`, name: "superset" },
      { command: String.raw`\supseteq`, name: "superset or equal" },
      { command: String.raw`\in`, name: "element of" },
      { command: String.raw`\notin`, name: "not element of" },
      { command: String.raw`\cup`, name: "union" },
      { command: String.raw`\cap`, name: "intersection" },
      { command: String.raw`\setminus`, name: "set minus" },
    ],
  },
  {
    name: "Big operators",
    entries: [
      { command: String.raw`\sum`, name: "sum" },
      { command: String.raw`\prod`, name: "product" },
      { command: String.raw`\int`, name: "integral" },
      { command: String.raw`\iint`, name: "double integral" },
      { command: String.raw`\iiint`, name: "triple integral" },
      { command: String.raw`\oint`, name: "contour integral" },
      { command: String.raw`\bigcup`, name: "big union" },
      { command: String.raw`\bigcap`, name: "big intersection" },
      { command: String.raw`\bigoplus`, name: "big direct sum" },
      { command: String.raw`\bigotimes`, name: "big tensor product" },
      { command: String.raw`\coprod`, name: "coproduct" },
      { command: String.raw`\lim`, name: "limit" },
      { command: String.raw`\limsup`, name: "limit superior" },
      { command: String.raw`\liminf`, name: "limit inferior" },
    ],
  },
  {
    name: "Arrows",
    entries: [
      { command: String.raw`\to`, name: "to" },
      { command: String.raw`\rightarrow`, name: "right arrow" },
      { command: String.raw`\leftarrow`, name: "left arrow" },
      { command: String.raw`\leftrightarrow`, name: "left right arrow" },
      { command: String.raw`\Rightarrow`, name: "implies (double right)" },
      { command: String.raw`\Leftarrow`, name: "double left arrow" },
      { command: String.raw`\Leftrightarrow`, name: "if and only if (double)" },
      { command: String.raw`\implies`, name: "implies" },
      { command: String.raw`\iff`, name: "if and only if" },
      { command: String.raw`\mapsto`, name: "maps to" },
      { command: String.raw`\uparrow`, name: "up arrow" },
      { command: String.raw`\downarrow`, name: "down arrow" },
      { command: String.raw`\nearrow`, name: "north east arrow" },
      { command: String.raw`\searrow`, name: "south east arrow" },
      { command: String.raw`\longrightarrow`, name: "long right arrow" },
    ],
  },
  {
    name: "Delimiters",
    entries: [
      { command: String.raw`\left( x \right)`, name: "parentheses" },
      { command: String.raw`\left[ x \right]`, name: "square brackets" },
      { command: String.raw`\left\{ x \right\}`, name: "curly braces" },
      { command: String.raw`\langle x \rangle`, name: "angle brackets" },
      { command: String.raw`\lceil x \rceil`, name: "ceiling" },
      { command: String.raw`\lfloor x \rfloor`, name: "floor" },
      { command: String.raw`\| x \|`, name: "norm / double bar" },
      { command: String.raw`\vert x \vert`, name: "absolute value / vertical bar" },
    ],
  },
  {
    name: "Accents & decorations",
    entries: [
      { command: String.raw`\hat{x}`, name: "hat" },
      { command: String.raw`\bar{x}`, name: "bar" },
      { command: String.raw`\vec{x}`, name: "vector" },
      { command: String.raw`\tilde{x}`, name: "tilde" },
      { command: String.raw`\dot{x}`, name: "dot" },
      { command: String.raw`\ddot{x}`, name: "double dot" },
      { command: String.raw`\widehat{xy}`, name: "wide hat" },
      { command: String.raw`\widetilde{xy}`, name: "wide tilde" },
      { command: String.raw`\overline{xy}`, name: "overline" },
      { command: String.raw`\underline{xy}`, name: "underline" },
      { command: String.raw`\overrightarrow{AB}`, name: "over right arrow" },
      { command: String.raw`\overbrace{xyz}`, name: "over brace" },
      { command: String.raw`\underbrace{xyz}`, name: "under brace" },
    ],
  },
  {
    name: "Fractions, roots & binomials",
    entries: [
      { command: String.raw`\frac{a}{b}`, name: "fraction" },
      { command: String.raw`\dfrac{a}{b}`, name: "display fraction" },
      { command: String.raw`\tfrac{a}{b}`, name: "text fraction" },
      { command: String.raw`\sqrt{x}`, name: "square root" },
      { command: String.raw`\sqrt[n]{x}`, name: "nth root" },
      { command: String.raw`\binom{n}{k}`, name: "binomial coefficient" },
      { command: String.raw`\dbinom{n}{k}`, name: "display binomial" },
    ],
  },
  {
    name: "Logic & set theory",
    entries: [
      { command: String.raw`\forall`, name: "for all" },
      { command: String.raw`\exists`, name: "there exists" },
      { command: String.raw`\nexists`, name: "there does not exist" },
      { command: String.raw`\neg`, name: "negation / not" },
      { command: String.raw`\land`, name: "logical and" },
      { command: String.raw`\lor`, name: "logical or" },
      { command: String.raw`\emptyset`, name: "empty set" },
      { command: String.raw`\varnothing`, name: "empty set (variant)" },
      { command: String.raw`\subseteq`, name: "subset or equal" },
      { command: String.raw`\supseteq`, name: "superset or equal" },
      { command: String.raw`\in`, name: "element of" },
      { command: String.raw`\notin`, name: "not element of" },
      { command: String.raw`\therefore`, name: "therefore" },
      { command: String.raw`\because`, name: "because" },
      { command: String.raw`\top`, name: "top / true" },
      { command: String.raw`\bot`, name: "bottom / false" },
      { command: String.raw`\vdash`, name: "proves / turnstile" },
      { command: String.raw`\models`, name: "models / entails" },
    ],
  },
  {
    name: "Calculus & analysis",
    entries: [
      { command: String.raw`\partial`, name: "partial derivative" },
      { command: String.raw`\nabla`, name: "nabla / del" },
      { command: String.raw`\infty`, name: "infinity" },
      { command: String.raw`\int`, name: "integral" },
      { command: String.raw`\oint`, name: "contour integral" },
      { command: String.raw`\sum`, name: "sum" },
      { command: String.raw`\prod`, name: "product" },
      { command: String.raw`\lim`, name: "limit" },
      { command: String.raw`\Delta`, name: "delta / change" },
      { command: String.raw`\mathrm{d}`, name: "upright differential d" },
      { command: String.raw`\prime`, name: "prime" },
      { command: String.raw`\circ`, name: "composition / ring" },
    ],
  },
  {
    name: "Structures (matrices & cases)",
    entries: [
      { command: String.raw`\begin{pmatrix}a&b\\c&d\end{pmatrix}`, name: "parenthesis matrix" },
      { command: String.raw`\begin{bmatrix}a&b\\c&d\end{bmatrix}`, name: "bracket matrix" },
      { command: String.raw`\begin{vmatrix}a&b\\c&d\end{vmatrix}`, name: "determinant matrix" },
      { command: String.raw`\begin{cases}a&x>0\\b&x\le0\end{cases}`, name: "cases / piecewise" },
    ],
  },
  {
    name: "Fonts & styles",
    entries: [
      { command: String.raw`\mathbb{R}`, name: "blackboard bold / real numbers" },
      { command: String.raw`\mathcal{L}`, name: "calligraphic" },
      { command: String.raw`\mathfrak{g}`, name: "fraktur" },
      { command: String.raw`\mathbf{v}`, name: "bold" },
      { command: String.raw`\mathrm{d}`, name: "roman / upright" },
      { command: String.raw`\mathsf{A}`, name: "sans serif" },
      { command: String.raw`\boldsymbol{\beta}`, name: "bold symbol" },
      { command: String.raw`\text{word}`, name: "text mode" },
    ],
  },
];
